<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta charset="utf-8">
  <script src="js/libs/jquery-2.1.3.js"></script>
  <script src="bootstrap/js/bootstrap.js"></script>
  <script src="bootstrap/js/bootstrap.min.js"></script>
  <script src="js/pushPop.js"></script>
  <script src="js/ajax.js"></script>
  <script src="js/pages.js"></script>
  <script src="js/nav_menus.js"></script>
  <script src="js/main.js"></script>
  <link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.css">
  <link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
  <header class="container">
    <section class="row" id="header-section">
      <nav class="navbar navbar-inverse navbar-fixed-top navbar-grey">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="home">Project</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <form class="search-form navbar-form navbar-right">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="search">
              </div>
              <button type="submit" class="btn btn-success">Search</button>
            </form>
          </div>
        </div>
      </nav>
    </section>
  </header>

  <div class="jumbotron">
  </div>

  <main class="container">
    <section class="row" id="main-section-row">

      <?php include("admin/admin.html"); ?>

      <section id="page" class="col-md-6">
      </section>

    </section>
  </main>

  <footer class="footer">
      <div class="container">
        <p>Footer.</p>
      </div>
    </footer>
  
</body>
</html>